const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),path=require('path');
const app=express(),db=new Database(path.join(__dirname,'madazon.db')),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE_THIS_SECRET_IN_PRODUCTION';
db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('buyer','seller','admin')),created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS shops(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT DEFAULT '');CREATE TABLE IF NOT EXISTS products(id INTEGER PRIMARY KEY AUTOINCREMENT,seller_id INTEGER NOT NULL,shop_name TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,price INTEGER NOT NULL,stock INTEGER NOT NULL,icon TEXT DEFAULT '📦',description TEXT DEFAULT '',active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS orders(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,total INTEGER NOT NULL,status TEXT DEFAULT 'pending',address TEXT NOT NULL,city TEXT NOT NULL,note TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,product_id INTEGER,product_name TEXT,price INTEGER,qty INTEGER,seller_id INTEGER);CREATE TABLE IF NOT EXISTS favorites(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,product_id INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,product_id));CREATE TABLE IF NOT EXISTS reviews(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,product_id INTEGER NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT DEFAULT '',created_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,product_id));CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,read INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);`);
app.use(cors());app.use(express.json({limit:'1mb'}));
const pub=u=>({id:u.id,name:u.name,email:u.email,role:u.role}),tok=u=>jwt.sign(pub(u),SECRET,{expiresIn:'7d'});
function auth(req,res,next){try{let h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error();req.user=jwt.verify(h.slice(7),SECRET);next()}catch(e){res.status(401).json({message:'Authentification requise.'})}}
function role(r){return(req,res,next)=>req.user.role===r?next():res.status(403).json({message:'Accès refusé.'})}
function notify(userId,title,message){db.prepare('INSERT INTO notifications(user_id,title,message) VALUES(?,?,?)').run(userId,title,message)}
app.get('/api/health',(q,s)=>s.json({ok:true,version:'9'}));
app.post('/api/auth/register',async(req,res)=>{let{name,email,password,role='buyer'}=req.body||{};if(!name||!email||!password||password.length<6||!['buyer','seller'].includes(role))return res.status(400).json({message:'Données invalides.'});try{let x=db.prepare('INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)').run(name.trim(),email.trim().toLowerCase(),await bcrypt.hash(password,12),role),u=db.prepare('SELECT * FROM users WHERE id=?').get(x.lastInsertRowid);res.status(201).json({token:tok(u),user:pub(u)})}catch(e){res.status(409).json({message:'Cet e-mail est déjà utilisé.'})}});
app.post('/api/auth/login',async(req,res)=>{let u=db.prepare('SELECT * FROM users WHERE email=?').get(String(req.body.email||'').trim().toLowerCase());if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({message:'Identifiants incorrects.'});res.json({token:tok(u),user:pub(u)})});
app.get('/api/me',auth,(q,s)=>s.json({user:db.prepare('SELECT id,name,email,role,created_at FROM users WHERE id=?').get(q.user.id)}));
app.patch('/api/me',auth,(q,s)=>{let{name}=q.body||{};if(!name||name.trim().length<2)return s.status(400).json({message:'Nom invalide.'});db.prepare('UPDATE users SET name=? WHERE id=?').run(name.trim(),q.user.id);s.json({user:db.prepare('SELECT id,name,email,role,created_at FROM users WHERE id=?').get(q.user.id)})});
app.get('/api/categories',(q,s)=>s.json({categories:db.prepare('SELECT category,COUNT(*) count FROM products WHERE active=1 GROUP BY category ORDER BY category').all()}));
app.get('/api/products',(q,s)=>{let{q:term,category,min,max,sort='newest'}=q.query,sql='SELECT p.id,p.seller_id,p.shop_name seller,p.name,p.category,p.price,p.stock,p.icon,p.description,p.created_at,COALESCE(ROUND(AVG(r.rating),1),0) rating,COUNT(r.id) reviews FROM products p LEFT JOIN reviews r ON r.product_id=p.id WHERE p.active=1',a=[];if(term){sql+=" AND lower(p.name||' '||p.description||' '||p.category) LIKE ?";a.push('%'+String(term).toLowerCase()+'%')}if(category&&category!=='Toutes'){sql+=' AND p.category=?';a.push(category)}if(Number.isFinite(+min)){sql+=' AND p.price>=?';a.push(+min)}if(Number.isFinite(+max)){sql+=' AND p.price<=?';a.push(+max)}sql+=' GROUP BY p.id ORDER BY '+(sort==='price_asc'?'p.price ASC':sort==='price_desc'?'p.price DESC':sort==='rating'?'rating DESC':'p.id DESC');s.json({products:db.prepare(sql).all(...a)})});
app.get('/api/products/:id',(req,res)=>{let p=db.prepare('SELECT p.*,COALESCE(ROUND(AVG(r.rating),1),0) rating,COUNT(r.id) reviews FROM products p LEFT JOIN reviews r ON r.product_id=p.id WHERE p.id=? AND p.active=1 GROUP BY p.id').get(+req.params.id);if(!p)return res.status(404).json({message:'Produit introuvable.'});res.json({product:p,reviews:db.prepare('SELECT r.rating,r.comment,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.id DESC').all(p.id)})});
app.get('/api/favorites',auth,(q,s)=>s.json({favorites:db.prepare('SELECT product_id FROM favorites WHERE user_id=?').all(q.user.id).map(x=>x.product_id)}));
app.post('/api/favorites/:id',auth,(q,s)=>{let p=db.prepare('SELECT id FROM products WHERE id=? AND active=1').get(+q.params.id);if(!p)return s.status(404).json({message:'Produit introuvable.'});let f=db.prepare('SELECT id FROM favorites WHERE user_id=? AND product_id=?').get(q.user.id,p.id);if(f)db.prepare('DELETE FROM favorites WHERE id=?').run(f.id);else db.prepare('INSERT INTO favorites(user_id,product_id) VALUES(?,?)').run(q.user.id,p.id);s.json({favorite:!f})});
app.post('/api/products/:id/reviews',auth,(q,s)=>{let{rating,comment=''}=q.body||{};if(!Number.isInteger(+rating)||+rating<1||+rating>5)return s.status(400).json({message:'Note de 1 à 5 requise.'});let p=db.prepare('SELECT id FROM products WHERE id=? AND active=1').get(+q.params.id);if(!p)return s.status(404).json({message:'Produit introuvable.'});let bought=db.prepare('SELECT 1 FROM order_items i JOIN orders o ON o.id=i.order_id WHERE i.product_id=? AND o.user_id=? LIMIT 1').get(p.id,q.user.id);if(!bought)return s.status(403).json({message:'Vous devez avoir acheté ce produit pour laisser un avis.'});db.prepare(`INSERT INTO reviews(user_id,product_id,rating,comment) VALUES(?,?,?,?) ON CONFLICT(user_id,product_id) DO UPDATE SET rating=excluded.rating,comment=excluded.comment`).run(q.user.id,p.id,+rating,String(comment).slice(0,500));s.json({ok:true})});
app.get('/api/notifications',auth,(q,s)=>s.json({notifications:db.prepare('SELECT * FROM notifications WHERE user_id=? ORDER BY id DESC LIMIT 30').all(q.user.id)}));
app.patch('/api/notifications/read',auth,(q,s)=>{db.prepare('UPDATE notifications SET read=1 WHERE user_id=?').run(q.user.id);s.json({ok:true})});
app.get('/api/seller/shop',auth,role('seller'),(q,s)=>s.json({shop:db.prepare('SELECT * FROM shops WHERE user_id=?').get(q.user.id)||null}));
app.post('/api/seller/shop',auth,role('seller'),(q,s)=>{let{name,description=''}=q.body;if(!name)return s.status(400).json({message:'Nom requis.'});let x=db.prepare('SELECT id FROM shops WHERE user_id=?').get(q.user.id);x?db.prepare('UPDATE shops SET name=?,description=? WHERE user_id=?').run(name.trim(),description,q.user.id):db.prepare('INSERT INTO shops(user_id,name,description) VALUES(?,?,?)').run(q.user.id,name.trim(),description);db.prepare('UPDATE products SET shop_name=? WHERE seller_id=?').run(name.trim(),q.user.id);s.json({ok:true})});
app.get('/api/seller/products',auth,role('seller'),(q,s)=>s.json({products:db.prepare('SELECT * FROM products WHERE seller_id=? AND active=1 ORDER BY id DESC').all(q.user.id)}));
app.post('/api/seller/products',auth,role('seller'),(q,s)=>{let{name,category,price,stock,icon='📦',description=''}=q.body,shop=db.prepare('SELECT name FROM shops WHERE user_id=?').get(q.user.id);if(!shop)return s.status(400).json({message:'Créez votre boutique d’abord.'});if(!name||!category||!Number.isInteger(+price)||+price<0||!Number.isInteger(+stock)||+stock<0)return s.status(400).json({message:'Données produit invalides.'});let x=db.prepare('INSERT INTO products(seller_id,shop_name,name,category,price,stock,icon,description) VALUES(?,?,?,?,?,?,?,?)').run(q.user.id,shop.name,name.trim(),category,+price,+stock,icon||'📦',description||'');s.status(201).json({id:x.lastInsertRowid})});
app.patch('/api/seller/products/:id',auth,role('seller'),(q,s)=>{let{name,category,price,stock,icon,description}=q.body||{};if(!name||!category||!Number.isInteger(+price)||+price<0||!Number.isInteger(+stock)||+stock<0)return s.status(400).json({message:'Données invalides.'});let x=db.prepare('UPDATE products SET name=?,category=?,price=?,stock=?,icon=?,description=? WHERE id=? AND seller_id=? AND active=1').run(name.trim(),category,+price,+stock,icon||'📦',description||'',+q.params.id,q.user.id);if(!x.changes)return s.status(404).json({message:'Produit introuvable.'});s.json({ok:true})});
app.delete('/api/seller/products/:id',auth,role('seller'),(q,s)=>{db.prepare('UPDATE products SET active=0 WHERE id=? AND seller_id=?').run(+q.params.id,q.user.iapp.listen(PORT,'0.0.0.0',()=>console.log('Madazon V9: http://0.0.0.0:'+PORT));d);s.json({ok:true})});
app.post('/api/orders',auth,(q,s)=>{let{items,address,city,note=''}=q.body||{};if(!items?.length||!address||!city)return s.status(400).json({message:'Panier et adresse requis.'});try{let tx=db.transaction(()=>{let total=0,rows=[];for(let i of items){let p=db.prepare('SELECT * FROM products WHERE id=? AND active=1').get(+i.id),qty=+i.qty;if(!p||!Number.isInteger(qty)||qty<1||qty>p.stock)throw Error('Stock insuffisant ou produit invalide.');total+=p.price*qty;rows.push([p,qty])}let o=db.prepare('INSERT INTO orders(user_id,total,status,address,city,note) VALUES(?,?,?,?,?,?)').run(q.user.id,total,'pending',address,city,note);for(let [p,qty] of rows){db.prepare('UPDATE products SET stock=stock-? WHERE id=?').run(qty,p.id);db.prepare('INSERT INTO order_items(order_id,product_id,product_name,price,qty,seller_id) VALUES(?,?,?,?,?,?)').run(o.lastInsertRowid,p.id,p.name,p.price,qty,p.seller_id);notify(p.seller_id,'Nouvelle commande','Une commande contient votre produit « '+p.name+' ».')}notify(q.user.id,'Commande créée','Votre commande #'+o.lastInsertRowid+' est en attente.');return db.prepare('SELECT * FROM orders WHERE id=?').get(o.lastInsertRowid)});const order=tx();s.status(201).json({order})}catch(e){s.status(400).json({message:e.message})}});
app.get('/api/orders',auth,(q,s)=>s.json({orders:db.prepare('SELECT * FROM orders WHERE user_id=? ORDER BY id DESC').all(q.user.id)}));
app.get('/api/orders/:id',auth,(q,s)=>{let o=db.prepare('SELECT * FROM orders WHERE id=? AND user_id=?').get(+q.params.id,q.user.id);if(!o)return s.status(404).json({message:'Commande introuvable.'});s.json({order:o,items:db.prepare('SELECT * FROM order_items WHERE order_id=?').all(o.id)})});
app.get('/api/seller/orders',auth,role('seller'),(q,s)=>s.json({orders:db.prepare('SELECT o.* FROM orders o JOIN order_items i ON i.order_id=o.id WHERE i.seller_id=? GROUP BY o.id ORDER BY o.id DESC').all(q.user.id)}));
app.patch('/api/seller/orders/:id',auth,role('seller'),(q,s)=>{let a=['pending','confirmed','shipped','delivered','cancelled'];if(!a.includes(q.body.status))return s.status(400).json({message:'Statut invalide.'});let x=db.prepare('SELECT o.user_id FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=? AND i.seller_id=?').get(+q.params.id,q.user.id);if(!x)return s.status(404).json({message:'Commande introuvable.'});db.prepare('UPDATE orders SET status=? WHERE id=?').run(q.body.status,+q.params.id);notify(x.user_id,'Commande mise à jour','La commande #'+q.params.id+' est maintenant « '+q.body.status+' ».');s.json({ok:true})});
app.get('/api/admin/overview',auth,role('admin'),(q,s)=>s.json({stats:{users:db.prepare('SELECT count(*) n FROM users').get().n,sellers:db.prepare("SELECT count(*) n FROM users WHERE role='seller'").get().n,products:db.prepare('SELECT count(*) n FROM products WHERE active=1').get().n,orders:db.prepare('SELECT count(*) n FROM orders').get().n},orders:db.prepare('SELECT o.*,u.name customer_name FROM orders o JOIN users u ON u.id=o.user_id ORDER BY o.id DESC LIMIT 30').all()}));

app.use(express.static(path.join(__dirname,'..')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','index.html')));
app.listen(PORT,'0.0.0.0',()=>console.log('Madazon V9: http://0.0.0.0:'+PORT));
